calendarr/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='calendarr'
urlpatterns = [
	path('',views.CalendarrHome.as_view(),name='calendarrhome_report'),
	path('repetitive_report/',views.RepetitiveReport.as_view(),name='repetitive_report'),
	path('get_report_data/',views.get_report_data,name='get_report_data_ajax'),
]

demo/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='demo'
urlpatterns = [
	path('listen_comport/',views.listen_comport,name='listen_comport'),
	path('port_listener/',views.port_listener,name='port_listener_ajax'),
	path('demo/',views.demo,name='demo_ajax'),
	
]

myERP/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from myERP import views


### path_part
app_name='myERP'
urlpatterns = [
	path('register/',views.MyRegisterView.as_view(),name='register'),
	path('login/',views.MyLoginView.as_view(),name='login'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout'),
	path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
	path('password_change/',auth_views.PasswordChangeView.as_view(),name='change-password'),
	path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
	path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
	path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
	path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
	path('register_validation/',views.RegisterValidationView.as_view(),name='register_validation'),
	
	path('add/<str:m_name>/',views.GlobalAddView.as_view(),name='global_add'),
	path('delete/<str:m_name>/<int:pk>/',views.GlobalDeleteView.as_view(),name='global_delete'),
	path('detail/<str:m_name>/<int:pk>/',views.GlobalDetailView.as_view(),name='global_detail'),
	path('list/<str:m_name>/',views.GlobalListView.as_view(),name='global_list'),
	path('update/<str:m_name>/<int:pk>/',views.GlobalUpdateView.as_view(),name='global_update'),
	
	path('',views.Index.as_view(),name='index'),
	path('home/',views.Home.as_view(),name='home'),
	path('admin/',admin.site.urls),
	path('authentication/',include('authentication.urls')),
	path('calendarr/',include('calendarr.urls')),
	path('constant/',include('constant.urls')),
	path('financial/',include('financial.urls')),
	path('main/',include('main.urls')),
	path('note/',include('note.urls')),
	path('people/',include('people.urls')),
	path('series/',include('series.urls')),
	path('demo/',include('demo.urls')),
	#path('temptry',temptry,name='temptry'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)

def handler404(request,exeption):
    return render(request,"error_page.html")
def handler403(request,exception):
    return render(request,"error_page.html")
def handler400(request,exception):
    return render(request,"error_page.html")
def handler500(request):
    return render(request,"error_page.html")

calendarr/models.py
# -*- coding: utf-8 -*-
### import_part
from financial.models import *
from functions.model import AttrDict
from functions.organizer import CodeGenerator


### models_part
class Event(models.Model):
	## fields
	name = models.CharField(null=True,blank=True,max_length=50,verbose_name='Adı')
	event_type = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=EventTypeLM,verbose_name='Etkinlik Tipi')
	date = models.DateField(null=True,blank=True,default=datetime.today,verbose_name='Tarih')
	time = models.TimeField(null=True,blank=True,max_length=5,verbose_name='Saat')
	duration = models.CharField(null=True,blank=True,max_length=5,verbose_name='Süre')
	loc = models.CharField(null=True,blank=True,max_length=200,verbose_name='Konum')
	desc = models.CharField(null=True,blank=True,max_length=500,verbose_name='Açıklaması')
	## class
	class Meta:
		db_table='event_m'
		ordering = ["-date","-time"]
	## def 1
	def __str__(self):
		return str(self.date)+" - "+str(self.name)
	## def 2
	def attr_dict(self,data_type):
		return AttrDict(self).get_attr_dict(data_type)
	## def 3
	def remote_attr_dict(self):
		return AttrDict(self).get_remote_attr_dict()

class Repetitive(models.Model):
	## fields
	name = models.CharField(null=True,blank=True,max_length=50,verbose_name='Adı')
	period_rate = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=PeriodLM,verbose_name='Periyot Sıkılığı')
	period_amount = models.CharField(null=True,blank=True,max_length=50,verbose_name='Periyot Miktarı')
	type = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=RepetitiveTypeLM,verbose_name='Tekrarlı Olay Türü')
	person = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=Person,verbose_name='Sahibi')
	corporation = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=CorporationLM,verbose_name='Firma')
	id_no = models.CharField(null=True,blank=True,max_length=50,verbose_name='Hesap No')
	change = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=Change,verbose_name='Aldım - Verdim')
	code = models.CharField(null=True,blank=True,max_length=100,verbose_name='Kısa Kod')
	desc = models.CharField(null=True,blank=True,max_length=500,verbose_name='Açıklaması')
	is_active = models.BooleanField(default=True,verbose_name='Aktif Mi?')
	## class
	class Meta:
		db_table='repetitive'
		ordering=["name"]
	## def 1
	def __str__(self):
		return str(self.name)+" - "+str(self.person)
	## def 2
	def attr_dict(self,data_type):
		return AttrDict(self).get_attr_dict(data_type)
	## def 3
	def remote_attr_dict(self):
		return AttrDict(self).get_remote_attr_dict()
	## def 4
	def generate_code(self):
		cg = CodeGenerator(self)
		self.code=cg.generate_repetitive_code()
		
class RepetitiveRecord(models.Model):
	## fields
	repetitive = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=Repetitive,verbose_name='Tekrarlı Olay')
	start_date = models.DateField(null=True,blank=True,verbose_name='Başlama Tarihi')
	end_date = models.DateField(null=True,blank=True,verbose_name='Bitiş Tarihi')
	last_date = models.DateField(null=True,blank=True,verbose_name='Son Ödeme Tarihi')
	amount = models.CharField(null=True,blank=True,max_length=10,verbose_name='Miktar')
	desc = models.CharField(null=True,blank=True,max_length=500,verbose_name='Açıklaması')
	transaction = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=Transaction,verbose_name='İşlem')
	is_active = models.BooleanField(default=True,verbose_name='Aktif Mi?')
	## class
	class Meta:
		db_table='repetitive_record'
		ordering=["-is_active","-last_date"]
	## def 1
	def __str__(self):
		return str(self.repetitive)+" - "+str(self.last_date)
	## def 2
	def attr_dict(self,data_type):
		return AttrDict(self).get_attr_dict(data_type)
	## def 3
	def remote_attr_dict(self):
		return AttrDict(self).get_remote_attr_dict()
	## def 4
	def generate_code(self):
		cg = CodeGenerator(self)
		self.desc=cg.generate_repetitive_record_code()

calendarr/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Event

calendarr/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import redirect,render
from functions.report import RepetitiveReport as RepReport,CalendarrReport
from django.views import View
from django.http import JsonResponse
from functions.auth_func import ModelQueryset
from functions.general import *

class CalendarrHome(View):
	template_name = "calendarr/calendarr_report.html"
	
	def get_context_data(self):
		context_data = HomeData(self.request).get_context_data()
		cr = CalendarrReport(self.request)
		context_data["title"] = "Takvim Raporu"
		context_data["rr_title"] = "İşleme Alınacak Tekrarlı Olaylar"
		context_data["rr_object_list"] = cr.get_repetitiverecord_data()
		context_data["er_title"] = "Yaklaşan Etkinlikler"
		context_data["er_object_list"] = cr.get_comingevent_data()
		return context_data
	
	def get(self, request):
		return render(request, self.template_name, context=self.get_context_data())
	
	
class RepetitiveReport(View):
	template_name = "calendarr/repetitive_report.html"
	
	def get_context_data(self):
		context_data = HomeData(self.request).get_context_data()
		context_data["title"] = "Tekrarlı İşlemler Raporu"
		mq=ModelQueryset(self.request)
		repetitive_list=mq.get_queryset("Repetitive")
		context_data["repetitive_list"]=repetitive_list
		return context_data
	
	def get(self, request):
		return render(request, self.template_name, context=self.get_context_data())


def get_report_data(request):
	rep_code=request.GET["rep_code"]
	rr=RepReport(request)
	id_list,name_list,data_list=rr.gather_info(rep_code)
	return JsonResponse({"id_list":id_list,"name_list":name_list,"data_list":data_list})

templates/calendarr/calendarr_report.html
{% extends "base.html" %}
{% load static template_funcs %}
{% block more_script %}
    <script>
        $('.row-link').dblclick(function() {
            window.location = this.getAttribute("href")
        });
    </script>
    <script>
    </script>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2>{{ rr_title }}</h2>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <tbody>
                                {% for rr_object in rr_object_list %}
                                    <tr class="row-link" href="{% url 'global_update' 'RepetitiveRecord' rr_object.id %}">
                                        <td style="max-width: 30ch">
                                            {{ rr_object }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                    </div>
                </div>
            <!-- /.card -->
            </div><div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2>{{ er_title }}</h2>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <tbody>
                                {% for er_object in er_object_list %}
                                    <tr class="row-link" href="{% url 'global_update' 'Event' er_object.id %}">
                                        <td style="max-width: 30ch">
                                            {{ er_object }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                    </div>
                </div>
            <!-- /.card -->
            </div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}

templates/calendarr/repetitive_report.html
{% extends "base.html" %}
{% load static %}
{% block header %}
    <div class="page-header">
        <select name="repetitive" id="id_repetitive" onchange="report_data(this)" data-target-input="1">
            {% for repetitive in repetitive_list %}
                <option value="{{ repetitive.code }}" data-title="{{ repetitive|safe }}">{{ repetitive }}</option>
            {% endfor %}
        </select>
    </div>
{% endblock %}
{% block content %}
    <div class="chart-body" id = "id_chart_body">
        <div class="card card-success" id="id_chart_card"  style="display: none">
            <div class="card-header">
                <h3 class="card-title" id="id_chart_title"></h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
            </div>
          <div class="card-body">
            <canvas id="id_chart" style="min-height: 275px"></canvas>
          </div>
          <!-- /.card-body -->
        </div>
    </div>
{% endblock %}
{% block more_css %}
  <!-- daterange picker -->
  <link rel="stylesheet" href="{% static "/plugins/daterangepicker/daterangepicker.css" %}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{% static "/plugins/select2/css/select2.min.css" %}">
  <link rel="stylesheet" href="{% static "/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
{% endblock %}
{% block more_script %}
<!-- ChartJS -->
<script src="{% static "/plugins/chart.js/Chart.min.js" %}"></script>
<!-- Select2 -->
<script src="{% static "/plugins/select2/js/select2.full.min.js" %}"></script>
<!-- InputMask -->
<script src="{% static "/plugins/moment/moment.min.js" %}"></script>
<script src="{% static "/plugins/inputmask/min/jquery.inputmask.bundle.min.js" %}"></script>
<!-- date-range-picker -->
<script src="{% static "/plugins/daterangepicker/daterangepicker.js" %}"></script>
    <script>
        $('select').select2({
            theme: 'bootstrap4'
        });
        function report_data(rep_code) {
            var chart_no=rep_code.dataset.targetInput;
            var chart_body = document.getElementById("id_chart_body");
            var chart_card = document.getElementById("id_chart_card");
            var new_chart_card = chart_card.cloneNode(true);
            new_chart_card.id = new_chart_card.id+"_"+chart_no
            new_chart_card.style.display = "inline";
            var new_title_id = new_chart_card.getElementsByTagName("h3")[0];
            new_title_id.id = new_title_id.id+"_"+chart_no
            var new_chart_id = new_chart_card.getElementsByTagName("canvas")[0];
            new_chart_id.id = new_chart_id.id+"_"+chart_no
            chart_body.appendChild(new_chart_card);

            $.ajax({
                url:"{% url 'calendarr:get_report_data_ajax' %}",
                data:{"rep_code":rep_code.value},
                dataType:'json',
                success:function(result) {
                    var chart_id = rep_code.dataset.targetInput;
                    var id_list=result["id_list"];
                    var name_list=result["name_list"];
                    var data_list=result["data_list"];
                    var barChartCanvas = $('#id_chart_'+chart_id).get(0).getContext('2d');
                    var barChartData        = {
                        labels: name_list,
                        datasets: [{
                            data: data_list,
                            backgroundColor : ['#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745','#28a745'],
                        }]
                    };
                    var barChartOptions     = {
                        maintainAspectRatio : false,
                        responsive : true,
                        datasetFill : false,
                        legend:{
                            display:false,
                        },
                        onClick: function(c,i) {
                                    var e = i[0];
                                    var index=e._index;
                                    var item_id= id_list[index];
                                    var label = this.data.labels[e._index];
                                    var data = this.data.datasets[0].data[e._index];
                                    window.open("/detail/RepetitiveRecord/"+item_id+"/")
                                },
						scales: {
							yAxes:[{
								ticks:{
									beginAtZero:true,
									}
								}]
							},
                    };
                    var barChart = new Chart(barChartCanvas, {
                        type: 'bar',
                        data: barChartData,
                        options: barChartOptions
                    });
                    var title_elem = document.getElementById("id_chart_title_"+chart_id);
                    title_elem.innerText = rep_code.options[rep_code.selectedIndex].text;
                    rep_code.dataset.targetInput = parseInt(rep_code.dataset.targetInput)+1
                }
            });
        }
    </script>
{% endblock %}