demo/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='demo'
urlpatterns = [
	path('listen_comport/',views.listen_comport,name='listen_comport'),
	path('port_listener/',views.port_listener,name='port_listener_ajax'),
	path('demo/',views.demo,name='demo_ajax'),
	
]

myERP/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from myERP import views


### path_part
app_name='myERP'
urlpatterns = [
	path('register/',views.MyRegisterView.as_view(),name='register'),
	path('login/',views.MyLoginView.as_view(),name='login'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout'),
	path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
	path('password_change/',auth_views.PasswordChangeView.as_view(),name='change-password'),
	path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
	path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
	path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
	path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
	path('register_validation/',views.RegisterValidationView.as_view(),name='register_validation'),
	
	path('add/<str:m_name>/',views.GlobalAddView.as_view(),name='global_add'),
	path('delete/<str:m_name>/<int:pk>/',views.GlobalDeleteView.as_view(),name='global_delete'),
	path('detail/<str:m_name>/<int:pk>/',views.GlobalDetailView.as_view(),name='global_detail'),
	path('list/<str:m_name>/',views.GlobalListView.as_view(),name='global_list'),
	path('update/<str:m_name>/<int:pk>/',views.GlobalUpdateView.as_view(),name='global_update'),
	
	path('',views.Index.as_view(),name='index'),
	path('home/',views.Home.as_view(),name='home'),
	path('admin/',admin.site.urls),
	path('authentication/',include('authentication.urls')),
	path('calendarr/',include('calendarr.urls')),
	path('constant/',include('constant.urls')),
	path('financial/',include('financial.urls')),
	path('main/',include('main.urls')),
	path('note/',include('note.urls')),
	path('people/',include('people.urls')),
	path('series/',include('series.urls')),
	path('demo/',include('demo.urls')),
	#path('temptry',temptry,name='temptry'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)

def handler404(request,exeption):
    return render(request,"error_page.html")
def handler403(request,exception):
    return render(request,"error_page.html")
def handler400(request,exception):
    return render(request,"error_page.html")
def handler500(request):
    return render(request,"error_page.html")

series/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='series'
urlpatterns = [
	path('change_state',views.change_state,name='change_state_ajax'),
	path('',views.SeriesHome.as_view(),name='serieshome_report')
]

series/models.py
# -*- coding: utf-8 -*-
### import_part
from main.models import *
from functions.model import AttrDict


### models_part
class Series(models.Model):
	## fields
	main_name = models.CharField(null=True,blank=True,max_length=50,verbose_name='Ana Seri Adı')
	name = models.CharField(null=True,blank=True,max_length=50,verbose_name='Seri Adı')
	second_name = models.CharField(null=True,blank=True,max_length=50,verbose_name='İkincil Adı')
	series_type = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=SeriesTypeLM,verbose_name='Seri Tipi')
	web_address = models.CharField(null=True,blank=True,max_length=100,verbose_name='Web Adresi')
	rate = models.CharField(null=True,blank=True,max_length=5,verbose_name='Puanı')
	current_eps = models.CharField(null=True,blank=True,max_length=3,verbose_name='Mevcut Bölüm')
	total_eps = models.CharField(null=True,blank=True,max_length=3,verbose_name='Toplam Bölüm')
	season = models.CharField(null=True,blank=True,max_length=2,verbose_name='Sezon Adedi')
	state = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=SeriesStateLM,verbose_name='Durumu')
	download = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=SeriesDownloadLM,verbose_name='İndirilebilirliği')
	start_date = models.DateField(null=True,blank=True,default=datetime.today,verbose_name='Başlama Tarihi')
	country = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=CountryLM,verbose_name='Ülkesi')
	director = models.CharField(null=True,blank=True,max_length=50,verbose_name='Yönetmeni')
	desc = models.CharField(null=True,blank=True,max_length=500,verbose_name='Açıklaması')
	## class
	class Meta:
		db_table='series_m'
		ordering=["name","season","current_eps"]
	## def 1
	def __str__(self):
		if self.second_name:
			return str(self.name) + " - " + str(self.second_name)
		elif self.season:
			return str(self.name) + " (" + str(self.season) + ". Sezon)"
		elif self.current_eps:
			return str(self.name) + " (" + str(self.current_eps) + ". Bölüm)"
		else:
			return str(self.name)
	## def 2
	def attr_dict(self,data_type):
		return AttrDict(self).get_attr_dict(data_type)
	## def 3
	def remote_attr_dict(self):
		return AttrDict(self).get_remote_attr_dict()

class SeriesGenre(models.Model):
	## fields
	series = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=Series,verbose_name='Seri')
	genre = models.ForeignKey(null=True,blank=True,on_delete=models.SET_NULL,to=SeriesGenreLM,verbose_name='Seri Türü')
	## class
	class Meta:
		db_table='seriesgenre_m'
		ordering=["series"]
	## def 1
	def __str__(self):
		return str(self.series) + "-" +str(self.genre)
	## def 2
	def attr_dict(self,data_type):
		return AttrDict(self).get_attr_dict(data_type)
	## def 3
	def remote_attr_dict(self):
		return AttrDict(self).get_remote_attr_dict()

class RelatedSeries(models.Model):
	## fields
	series1 = models.CharField(null=True,blank=True,max_length=50,verbose_name='Seri 1')
	series2 = models.CharField(null=True,blank=True,max_length=50,verbose_name='Seri 2')
	desc = models.CharField(null=True,blank=True,max_length=500,verbose_name='Açıklaması')
	## class
	class Meta:
		db_table='relatedseries_m'
		ordering=["series1","series2"]
	## def 1
	def __str__(self):
		return str(self.series1) + "-" +str(self.series2) + "-" + str(self.desc)
	## def 2
	def attr_dict(self,data_type):
		return AttrDict(self).get_attr_dict(data_type)
	## def 3
	def remote_attr_dict(self):
		return AttrDict(self).get_remote_attr_dict()

series/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views import View
from functions.report import *
from functions.general import *


def change_state(request):
	if "series_id" in request.GET:
		series_id=request.GET["series_id"]
		series=Series.objects.get(pk=series_id)
	else:
		series=None
	if "state_id" in request.GET:
		state_id=request.GET["state_id"]
	else:
		state_id = 4
	try:
		series.state_id = state_id
		series.save()
		return JsonResponse({"status": True})
	except:
		return JsonResponse({"status":False})

class SeriesHome(View):
	template_name = "series/series_report.html"

	def get_context_data(self):
		context_data = HomeData(self.request).get_context_data()
		context_data["title"] = "Seri Raporu"
		context_data["state_list"] = SeriesStateLM.objects.all().order_by("desc")
		return context_data
	
	def get(self, request):
		return render(request, self.template_name, context=self.get_context_data())

templates/series/series_box.html
<div class="card card-success" style="max-height: 500px">
    <div class="card-header">
        <div class="card-tools float-left">
            <h2 class="card-title"><a href="{% url "global_list" "Series" %}?state={{ state|safe }}" target="_blank" style="color: white">{{ state }}</a></h2>
        </div>
        <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 250px;">
                <input type="text" name="search_text" class="form-control float-right" placeholder="Arama" id="search_text_{{ state.id }}" onkeyup="filter_table({{ state.id }})">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0" style="max-height: 500px;">
        <table class="table table-hover text-nowrap" id="table_{{ state.id }}">
            <tbody >
                {% for s_object in s_object_list %}
                    <tr class="row-link" href="{% url 'global_detail' 'Series' s_object.id %}">
                        <td style="max-width: 10ch">
                            {{ s_object.series_type|safe }}
                        </td>
                        <td style="max-width: 40ch">
                            <a href="{{ s_object.web_address|safe }}" target="_blank" style="color: black">{{ s_object|safe|slice:"0:50" }}</a>
                        </td>
                        <td style="max-width: 10ch">
                            {{ s_object.start_date|safe }}
                        </td>
                        {% if s_object.state.id != 1 %}
                            <td onclick="change_state({{ s_object.id }},1)" style="max-width: 5ch" title="İzlemeyi Tamamladıklarım">
                                <i class="fa fa-check"></i>
                            </td>
                        {% endif %}
                        {% if s_object.state.id != 2 %}
                            <td onclick="change_state({{ s_object.id }},2)" style="max-width: 5ch" title="İzlemeyi Sürdürdüklerim">
                                <i class="fa fa-play"></i>
                            </td>
                        {% endif %}
                        {% if s_object.state.id != 3 %}
                            <td onclick="change_state({{ s_object.id }},3)" style="max-width: 5ch" title="İzlemeyi Bıraktıklarım">
                                <i class="fa fa-ban"></i>
                            </td>
                        {% endif %}
                        {% if s_object.state.id != 4 %}
                            <td onclick="change_state({{ s_object.id }},4)" style="max-width: 5ch" title="İzlemeyi Planladıklarım">
                                <i class="fa fa-tag"></i>
                            </td>
                        {% endif %}
                        {% if s_object.state.id != 5 %}
                            <td onclick="change_state({{ s_object.id }},5)" style="max-width: 5ch" title="Beklemeye Aldıklarım">
                                <i class="fa fa-pause"></i>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
    </div>
</div>

templates/series/series_report.html
{% extends "base.html" %}
{% load static template_funcs %}
{% block more_script %}
    <script>
        $('.row-link').dblclick(function() {
            window.location = this.getAttribute("href")
        });
    </script>
    <script>
    function change_state(series_id,state_id) {
        $.ajax({
            url:"{% url 'series:change_state_ajax' %}",
            data:{"series_id":series_id,"state_id":state_id},
            dataType:'json',
            success:function(result) {
                console.log(result);
                var status = result["status"];
                if (status) {
                    window.location.reload()
                }
            }
        });
    }
    </script>
    <script>
        function filter_table(state_id) {
            var input, filter, table, tr, td, i, txtValue,k,td_list;
            input = document.getElementById("search_text_"+state_id);
            filter = input.value.toLowerCase();
            table = document.getElementById("table_" + state_id);
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td_list = tr[i].getElementsByTagName("td");
                var result="none"
                for (k = 0; k< 5;k++){
                    td=td_list[k]
                    if (td) {
                        txtValue = td.textContent || td.innerText;
                        if (txtValue.toLowerCase().indexOf(filter) > -1) {
                            result = "";
                        }
                    }
                }
                tr[i].style.display = result
            }
        }
    </script>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            {% for state in state_list %}
                <div class="col-6">
                    {% get_series_list state %}
                <!-- /.card -->
                </div>
            {% endfor %}
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}