demo/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='demo'
urlpatterns = [
	path('listen_comport/',views.listen_comport,name='listen_comport'),
	path('port_listener/',views.port_listener,name='port_listener_ajax'),
	path('demo/',views.demo,name='demo_ajax'),
	
]

myERP/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from myERP import views


### path_part
app_name='myERP'
urlpatterns = [
	path('register/',views.MyRegisterView.as_view(),name='register'),
	path('login/',views.MyLoginView.as_view(),name='login'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout'),
	path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
	path('password_change/',auth_views.PasswordChangeView.as_view(),name='change-password'),
	path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
	path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
	path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
	path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
	path('register_validation/',views.RegisterValidationView.as_view(),name='register_validation'),
	
	path('add/<str:m_name>/',views.GlobalAddView.as_view(),name='global_add'),
	path('delete/<str:m_name>/<int:pk>/',views.GlobalDeleteView.as_view(),name='global_delete'),
	path('detail/<str:m_name>/<int:pk>/',views.GlobalDetailView.as_view(),name='global_detail'),
	path('list/<str:m_name>/',views.GlobalListView.as_view(),name='global_list'),
	path('update/<str:m_name>/<int:pk>/',views.GlobalUpdateView.as_view(),name='global_update'),
	
	path('',views.Index.as_view(),name='index'),
	path('home/',views.Home.as_view(),name='home'),
	path('admin/',admin.site.urls),
	path('authentication/',include('authentication.urls')),
	path('calendarr/',include('calendarr.urls')),
	path('constant/',include('constant.urls')),
	path('financial/',include('financial.urls')),
	path('main/',include('main.urls')),
	path('note/',include('note.urls')),
	path('people/',include('people.urls')),
	path('series/',include('series.urls')),
	path('demo/',include('demo.urls')),
	#path('temptry',temptry,name='temptry'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)

def handler404(request,exeption):
    return render(request,"error_page.html")
def handler403(request,exception):
    return render(request,"error_page.html")
def handler400(request,exception):
    return render(request,"error_page.html")
def handler500(request):
    return render(request,"error_page.html")

demo/models.py
# -*- coding: utf-8 -*-
### import_part
from django.contrib.auth.models import User

from functions.model import AttrDict

demo/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from functions.demo import SerialListener
from django.http import JsonResponse
from functions.general import *


def listen_comport(request):
    template_name="demo/comport_listener.html"
    comport_list=SerialListener().get_comport_list()
    context_data = HomeData(self.request).get_context_data()
    context_data["comport_list"]=comport_list
    context_data["title"]="Com Port Dinleme"
    return render(request, template_name, context=context_data)
    
def port_listener(request):
    if "p_name" not in request.GET:
        data="None"
    else:
        p_name=request.GET["p_name"]
        sp = SerialListener(p_name)
        sp.set_timeout(sp.serial_port,3)
        data = sp.get_data(sp.serial_port)
        sp.close_port(sp.serial_port)
    return JsonResponse({"data":data})
    
def demo(request):
    sp=SerialListener()
    sp.demo()
    return render(request, "demo/demo.html")

templates/demo/comport_listener.html
{% extends "base.html" %}
{% load static template_funcs %}
{% block more_script %}
<script>
	function create_item(data){
		let p_item = document.createElement('p');
			p_item.textContent = data;
		return p_item;
	};

    function report_data(p_name) {
        $.ajax({
            url:"{% url 'demo:port_listener_ajax' %}",
            data:{"p_name":p_name},
            dataType:'json',
            success:function(result) {
				var elem = document.getElementById("id_comport_data");
				elem.value = result["data"]
				<!-- elem.appendChild(create_item(result["data"])); -->
				var header = document.getElementById("com_header");
				header.innerText = p_name;
            }
        });
    };
	function run_flow(){
		
		setInterval(		
		function(){
		var value1 = document.getElementById("id_port_select").value;
		report_data(value1); }, 
		7000);
	}
	window.onload = run_flow()
</script>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
			<div class="card card-success" style="max-height: 500px">
				<div class="card-header">
					<div class="card-tools float-left" style="max-width: 250px;">
						<h2 class="card-title"><span id="com_header"></span></h2>
					</div>
					<div class="card-tools" style="max-width: 250px;">
						<div class="input-group input-group-sm">
								<select class="form-control" name="port_select" id="id_port_select">
									{% for port in comport_list %}
										<option value="{{ port.name }}">{{ port.name }}</option>
									{% endfor %}
								</select>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="data-viewer">
						<input type="text" name="comport_data" class="form-control float-right" id="id_comport_data" disabled>
					</div>
				</div>
			</div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}

templates/demo/demo.html
{% extends "base.html" %}
{% load static template_funcs %}
{% block more_script %}

{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
			<div class="card card-success" style="max-height: 500px">
				<div class="card-header">
					<div class="card-tools float-left" style="max-width: 250px;">
						<h2 class="card-title"><span id="com_header"></span></h2>
					</div>
					<div class="card-tools" style="max-width: 250px;">
						<div class="input-group input-group-sm">
								<select class="form-control" name="port_select" id="id_port_select">
									{% for port in comport_list %}
										<option value="{{ port.name }}">{{ port.name }}</option>
									{% endfor %}
								</select>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="data-viewer">
						<input type="text" name="comport_data" class="form-control float-right" id="id_comport_data" disabled>
					</div>
				</div>
			</div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
{% endblock %}