demo/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='demo'
urlpatterns = [
	path('listen_comport/',views.listen_comport,name='listen_comport'),
	path('port_listener/',views.port_listener,name='port_listener_ajax'),
	path('demo/',views.demo,name='demo_ajax'),
	
]

financial/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.urls import path
from . import views


### path_part
app_name='financial'
urlpatterns = [
	path('',views.FinancialHome.as_view(),name='financialhome_report'),
	path('get_report_data/',views.get_report_data,name='get_report_data_ajax'),
	path('build_transaction_history/',views.build_transaction_history,name='build_transaction_history_function'),
	path('multi_transaction_add/',views.MultiTransactionAdd.as_view(),name='multi_transaction_add_function'),
	path('transaction_category_report/',views.CategoryReport.as_view(),name='transaction_category_report'),
	path('get_category_report_data/',views.get_category_report_data,name='get_category_report_data_ajax'),
]

myERP/urls.py
# -*- coding: utf-8 -*-
### import_part
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from myERP import views


### path_part
app_name='myERP'
urlpatterns = [
	path('register/',views.MyRegisterView.as_view(),name='register'),
	path('login/',views.MyLoginView.as_view(),name='login'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout'),
	path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
	path('password_change/',auth_views.PasswordChangeView.as_view(),name='change-password'),
	path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
	path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
	path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
	path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
	path('register_validation/',views.RegisterValidationView.as_view(),name='register_validation'),
	
	path('add/<str:m_name>/',views.GlobalAddView.as_view(),name='global_add'),
	path('delete/<str:m_name>/<int:pk>/',views.GlobalDeleteView.as_view(),name='global_delete'),
	path('detail/<str:m_name>/<int:pk>/',views.GlobalDetailView.as_view(),name='global_detail'),
	path('list/<str:m_name>/',views.GlobalListView.as_view(),name='global_list'),
	path('update/<str:m_name>/<int:pk>/',views.GlobalUpdateView.as_view(),name='global_update'),
	
	path('',views.Index.as_view(),name='index'),
	path('home/',views.Home.as_view(),name='home'),
	path('admin/',admin.site.urls),
	path('authentication/',include('authentication.urls')),
	path('calendarr/',include('calendarr.urls')),
	path('constant/',include('constant.urls')),
	path('financial/',include('financial.urls')),
	path('main/',include('main.urls')),
	path('note/',include('note.urls')),
	path('people/',include('people.urls')),
	path('series/',include('series.urls')),
	path('demo/',include('demo.urls')),
	#path('temptry',temptry,name='temptry'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)

def handler404(request,exeption):
    return render(request,"error_page.html")
def handler403(request,exception):
    return render(request,"error_page.html")
def handler400(request,exception):
    return render(request,"error_page.html")
def handler500(request):
    return render(request,"error_page.html")

templates/base.html
{% load static %}
{% load template_funcs %}
<!DOCTYPE html>
<html lang="tr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="chrome">
  <title>{{ title }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "/plugins/fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static "/dist/css/ionicons.css" %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "/dist/css/adminlte.min.css" %}">
    {% block more_css %}

    {% endblock %}

</head>
<body class="hold-transition sidebar-mini sidebar-collapse">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
        <div class="">

        </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- User Dropdown Menu -->
                <li class="nav-item">
                    {% if request.user.is_authenticated  %}
                        <a href="#" class="nav-link" data-toggle="dropdown">{{ request.user.first_name }} {{ request.user.last_name }}
                            <img src="{{ profile_pic_path }}" alt="" height="30px">
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <a href="{% url "global_detail" "User" request.user.id %}" class="dropdown-item">
                                <i class="far fa-user"></i>
                                Profil
                            </a>
                            <a href="{% url "logout" %}" class="dropdown-item">
                                <i class="far fa-sign-out"></i>
                                Çıkış
                            </a>
                        </div>
                    {% else %}
                        <a href="{% url "login" %}" class="nav-link">
                            <i class="far fa-sign-in-alt"></i>
                            Giriş Yap
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{% url "home" %}" class="brand-link">
                <img src="{% static "/dist/img/AdminLTELogo.png" %}"
                    alt="AdminLTE Logo"
                    class="brand-image img-circle elevation-3"
                    style="opacity: .8">
                <span class="brand-text font-weight-light">MyERP</span>
            </a>
            {% if request.user.is_authenticated  %}
                <!-- Sidebar Menu -->
                {% get_sidebar request %}
                <!-- /.sidebar-menu -->
            {% endif %}
        <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>{{ title }}</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-lg-right">
                                {% block header %}

                                {% endblock %}
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                {% block content %}

                {% endblock %}
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
<!-- jQuery -->
<script src="{% static "/plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
{% block more_script %}

{% endblock %}
<!-- AdminLTE App -->
<script src="{% static "/dist/js/adminlte.min.js" %}"></script>
</body>
</html>

templates/error_page.html
{% extends "base.html" %}
{% load static %}

{% block more_script %}
    <script>
        var countDownDate =  new Date().getTime()+10000;
        var x = setInterval(function() {
          // Get today's date and time
          var now = new Date().getTime();

          // Find the distance between now and the count down date
          var distance = Math.floor((countDownDate - now) / (1100));

          // Output the result in an element with id="demo"
          document.getElementById("counter").innerHTML = distance;

          // If the count down is over, write some text
          if (distance < 0) {
            clearInterval(x);
            window.location="/home";
          }
        }, 1000);
    </script>
{% endblock %}

{% block content %}
<div>
    <p><h1>Hata Sayfası</h1></p>
    <div class="row">
        <p>Böyle Bir Sayfa Bulunmamaktadır&nbsp;<div id="counter"></div>&nbsp;saniye içinde <a     href="{% url "home" %}"> Ana Sayfa</a>'ya yönlendirileceksiniz</p>
    </div>
</div>
{% endblock %}

templates/global_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-xl-4 col-lg-6">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h1 class="m-0 font-weight-bold text-primary">{{ delete_title }}</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h4>{{ object }}</h4>
                        <h6 class="align-content-center">Silmek İstiyor musunuzu?</h6>
                        <div class="row justify-content-around">
                            <button class="btn btn-danger btn-icon-split" type="submit">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">Evet</span>
                            </button>
                            <button class="btn btn-success btn-icon-split" type="button" onclick="window.location='{% url "global_detail" m_name object.id %}'">
                                <span class="icon text-white-50">
                                    <i class="fas fa-check"></i>
                                </span>
                                <span class="text">Hayır</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/global_detail.html
{% extends "base.html" %}
{% load static template_funcs %}
{% block header %}
    <div class="col-lg-3"><a href="{% url "global_add" m_name %}" class="btn btn-block btn-outline-secondary">Yeni Ekle</a></div>
    <div class="col-lg-3"><a href="{% url "global_update" m_name object.id %}" class="btn btn-block btn-outline-secondary">Bilgiyi Düzenle</a></div>
    <div class="col-lg-3"><a href="{% url "global_delete" m_name object.id %}" class="btn btn-block btn-outline-secondary">Bilgiyi Sil</a></div>
    <div class="col-lg-3"><a href="{% url "global_list" m_name %}" class="btn btn-block btn-outline-secondary">{{ list_title }}</a></div>
{% endblock %}
{% block more_css %}
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static "plugins/select2/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
{% endblock %}
{% block more_script %}
    <!-- Select2 -->
    <script src="{% static "plugins/select2/js/select2.full.min.js" %}"></script>
    <!-- InputMask -->
    <script src="{% static "plugins/moment/moment.min.js" %}"></script>
    <script src="{% static "plugins/inputmask/min/jquery.inputmask.bundle.min.js" %}"></script>
    <script>
    </script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card card-secondary">
                <div class="card-header d-flex p-0">
                    <h3 class="card-title p-3">{{ title }}</h3>
                    {% get_page_list request %}
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="column col-xl-8" style="column-count: 2">
                            {% for field in fields %}
                                {% if field.name == "web_address" %}
                                    <div class="row" style="display: flex" id="{{ field.name }}">
                                        <span style="flex: 1"><strong>{{ field.verbose_name }}:</strong> </span>
                                        <span style="flex: 1"><a href="{% get_attr_value2 object field "Detail" %}">{% get_attr_value2 object field "Detail" %}</a></span>
                                    </div>
                                {% elif field.to == None %}
                                    <div class="row" style="display: flex" id="{{ field.name }}">
                                        <span style="flex: 1"><strong>{{ field.verbose_name }}:</strong> </span>
                                        <span style="flex: 1">{% get_attr_value2 object field "Detail" %}</span>
                                    </div>
                                {% else %}
                                    <div class="row" style="display: flex" id="{{ field.name }}">
                                        <span style="flex: 1"><strong>{{ field.verbose_name }}:</strong> </span>
                                        <span style="flex: 1"><a href="/detail/{{ field.to }}/{% get_attr_value2 object field "Detail" key="id" %}">{% get_attr_value2 object field "Detail" %}</a></span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="column col-xl-4">
                            {% for field,object_list in object.remote_attr_dict.items %}
                                <div class="row" id="{{ field.model.name }}">
									<div class="col-xl-12">
										<strong><a href="{% url 'global_list' field.model.name %}?{{ field.name }}_id={{ object.id }}" class="show_all">{{ field.model.list_title }}</a></strong>
										<a href="{% url 'global_add' field.model.name  %}?{{ field.name }}={{ object.id }}" id="add_{{ field.model.name }}" class="add_item"><i class="fa fa-plus"></i></a>
									</div>
									<div class="col-xl-12">
										<ul>
											{% for obj in object_list %}
												<a href="{% url 'global_detail' field.model.name obj.id %}"><li>{{ obj }}</li></a>
											{% endfor %}
										</ul>
									</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/global_form.html
{% extends "base.html" %}
{% load static %}
{% block more_css %}
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static "plugins/select2/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
{% endblock %}
{% block more_script %}
    <!-- Select2 -->
    <script src="{% static "plugins/select2/js/select2.full.min.js" %}"></script>
    <!-- InputMask -->
    <script src="{% static "plugins/moment/moment.min.js" %}"></script>
    <script src="{% static "plugins/inputmask/min/jquery.inputmask.bundle.min.js" %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
    <script>
        $(function () {
            $('.date').datetimepicker({
                locales:'tr',
                format:  "YYYY-MM-DD",
                todayHighlight:true,
                pickTime:false,
                pickDate: true,
                buttons: {
                    showToday: true,
                },
                tooltips: {
                    today:"Bugün",
                }
            });
            $('.time').datetimepicker({
                locale :'tr',
                format:  "HH:mm",
                pickDate: false,
                use24hours: true,
             });
            $('select').select2({
                theme: 'bootstrap4'
            });
        });
    </script>
{% endblock %}
{% block header %}
    <a href="{% url "global_list" m_name %}" class="btn  btn-block btn-outline-secondary">{{ list_title }}</a>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">{{ form_title }}</h3>
                    </div>
                    <form method="post" class="user" id="form_record">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="row justify-content-end">
                                <button class="btn btn-secondary btn-icon-split" type="submit">
                                    <span class="text">Kaydet</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static template_funcs %}
{% block more_css %}
    <!-- daterange picker -->
    <link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static "plugins/select2/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
{% endblock %}
{% block more_script %}
    <!-- ChartJS -->
    <script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
    <!-- Select2 -->
    <script src="{% static "plugins/select2/js/select2.full.min.js" %}"></script>
    <!-- InputMask -->
    <script src="{% static "plugins/moment/moment.min.js" %}"></script>
    <script src="{% static "plugins/inputmask/min/jquery.inputmask.bundle.min.js" %}"></script>
    <!-- date-range-picker -->
    <script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
    <script>
        //-------------
        //- DONUT CHART
        //-------------
        // Get context with jQuery - using jQuery's .get() method.
        function report_data(chart_id,period,field,m_name) {
            $.ajax({
                url:"{% url 'financial:get_report_data_ajax' %}",
                data:{"period":period,"m_name":m_name,"field":field},
                dataType:'json',
                success:function(result) {
					var id_list = result["id_list"];
                    var name_list=result["name_list"];
                    var data_list=result["data_list"];
                    var donutChartCanvas = $('#'+chart_id).get(0).getContext('2d');
                    var donutData        = {
                        labels: name_list,
                        datasets: [{
                            data: data_list,
                            backgroundColor : ['#C60000','#f56954','#C68D00','#f39c12','#00A763','#00B2B4','#00c0ef', '#3c8dbc', '#d2d6de','#000000'],
                        }]
                    };
                    var donutOptions     = {
                        maintainAspectRatio : false,
                        responsive : true,
                        legend:{
                            position:'right',
                            onClick:function (e,legendItem) {
                                var record_id=id_list[legendItem.index];
                                window.open("/detail/"+m_name+"/"+record_id)
                            },
                            labels:{
                                generateLabels: function(chart) {
                                    var data = chart.data;
                                    if (data.labels.length && data.datasets.length) {
                                        return data.labels.map(function(label, i) {
                                            var meta = chart.getDatasetMeta(0);
                                            var style = meta.controller.getStyle(i);
                                            return {
                                                text: label+':  '+data_list[i],
                                                fillStyle: style.backgroundColor,
                                                strokeStyle: style.borderColor,
                                                lineWidth: style.borderWidth,
                                                hidden: isNaN(data.datasets[0].data[i]) || meta.data[i].hidden,
                                                // Extra data used for toggling the correct item
                                                index: i
                                            };
                                        });
                                    }
                                    return [];
                                }
                            }
                        }
                    };
                    //Create pie or douhnut chart
                    // You can switch between pie and douhnut using the method below.
                    var donutChart = new Chart(donutChartCanvas, {
                        type: 'doughnut',
                        data: donutData,
                        options: donutOptions
                    })
                }
            });
        };
        if (document.getElementById("chart1")){
            window.onload=report_data('chart1',30,'name','Account',);
        };
    </script>
    <script>
        $('.row-link').dblclick(function() {
            window.location = this.getAttribute("href")
        });
    </script>
    <script>
        function filter_table(state_id) {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("search_text_"+state_id);
            filter = input.value.toUpperCase();
            table = document.getElementById("table_" + state_id);
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-lg-6">
                    <div class="card card-success" style="max-height: 500px">
                        <div class="card-header">
                            <h3 class="card-title">İşleme Alınacak Tekrarlı Olaylar</h3>
                            <div class="card-tools">
                                <div class="input-group input-group-sm" style="width: 250px;">
                                    <input type="text" name="search_text" class="form-control float-right" placeholder="Arama" id="search_text_1" onkeyup="filter_table(1)">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                                </div>
                            </div>
                        </div>
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap" id="table_1">
                                <tbody>
                                    {% for rr_object in rr_object_list %}
                                        <tr class="row-link" href="{% url 'global_update' 'RepetitiveRecord' rr_object.id %}">
                                            <td style="max-width: 30ch">
                                                {{ rr_object|safe }}
                                            </td>
                                            <td style="max-width: 30ch">
                                                {{ rr_object.last_date }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card card-success" style="max-height: 500px">
                        <div class="card-header">
                            <h3 class="card-title">Mevcut Hesap Durumu</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <canvas id="chart1" style="min-height: 400px; height: 400px; max-height: 400px; max-width: 100%;"></canvas>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card card-success" style="max-height: 500px">
                        <div class="card-header">
                            <h3 class="card-title">Sık Görüşülen Kişiler</h3>
                            <div class="card-tools">
                                <div class="input-group input-group-sm" style="width: 250px;">
                                    <input type="text" name="search_text" class="form-control float-right" placeholder="Arama" id="search_text_3" onkeyup="filter_table(3)">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap" id="table_3">
                                <tbody>
                                    {% for f_object in f_object_list %}
                                        <tr class="row-link" href="{% url 'global_detail' 'Person' f_object.0.id %}">
                                            <td style="max-width: 30ch">
                                                {% if f_object.1 %}
                                                    <img src="{{ f_object.1 }}" style="width:30px;height:30px;">
                                                {% endif %}
                                            </td>
                                            <td>
                                                <p>{{ f_object.0 }}</p>
                                            </td>
                                            <td>
                                                {% for key,value in f_object.0.remote_attr_dict.items %}
                                                    {% if key.model.name == "PersonPhone" %}
                                                        {% for item in value %}
                                                            <p><a href="tel:{{ item.phone_number }}">{{ item|safe }}</a></p>
                                                        {% endfor %}
                                                    {% elif key.model.name == "PersonEmail"%}
                                                        {% for item in value %}
                                                            <p><a href="mailto:{{ item.email }}">{{ item|safe }}</a></p>
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                        </div>
                    </div>
                <!-- /.card -->
                </div>
                <div class="col-lg-6">
                    {% get_series_list state %}
                </div>
            </div>
        {% else %}
        {% endif %}
    </div>
{% endblock %}

templates/page_list.html
{% load template_funcs %}
{% if ability == "List" %}
    <ul class="pagination pagination-sm m-0 float-right">
        {% for item in page_info %}
            <li class="page-item"><a class="page-link" href="{{ item.0 }}" id="page_{{ item.1 }}">{{ item.2 }}</a></li>
        {% endfor %}
    </ul>
{% elif ability == "Detail" %}
    <ul class="nav nav-pills ml-auto p-2">
        <li class="nav-item">
            <div class="btn-group">
                <a href="{{ page_info.0 }}" id="first_page"  class="btn btn-default"><i class="fas fa-arrow-alt-circle-left" style="color: #6c757d;"></i></a>
                <a href="{{ page_info.1 }}" id="previous_page"  class="btn btn-default"><i class="fas fa-arrow-left" style="color: #6c757d;"></i></a>
                <a href="#" id="cur_page"  class="btn btn-block font-weight-bold">{{ page_info.2 }}</a>
                <a href="{{ page_info.3 }}" id="next_page" class="btn btn-default"><i class="fas fa-arrow-right" style="color: #6c757d;"></i></a>
                <a href="{{ page_info.4 }}" id=last_page" class="btn btn-default"><i class="fas fa-arrow-alt-circle-right" style="color: #6c757d;"></i></a>
            </div>
        </li>
    </ul>
{% endif %}